language: node_js
node_js:
  - '8'
cache: yarn
script:
  - yarn lint
  - yarn test
  - yarn build
install:
  - yarn install
jobs:
  include:
    - stage: test
      node_js: '8'
      script: yarn test
branches:
  only:
    - master
